name = "SCGAN"

[hyper_params]
num_epochs = 130
lr = 0.0001
device = "cuda"
batch_size = 16
beta = 0.001
scale_factor = 2

[generator_params]
large_kernel_size = 9
small_kernel_size = 3
n_intermediate_channels = 64
n_blocks = 16
scale_factor = 2
in_channels = 3

[discriminator_params]
kernel_size = 3
n_channels = 64
n_blocks = 8
fc_size = 1024
in_channels = 3

[truncated_vgg19_params]
i = 5
j = 4

[version_info]
BIA_G8 = "0.0.1"
numpy = "1.23.5"
sklearn = "1.1.3"
joblib = "1.2.0"
xgboost = "1.7.1"
matplotlib = "3.6.2"
skimage = "0.19.3"
tomli = "2.0.1"
tomli-w = "1.0.0"
torch = "1.13.0.post200"
python = "3.8.15"

[metadata]
time_gmt = "Sun Dec 11 19:24:33 2022"
time_local = "Mon Dec 12 03:24:33 2022"

[metadata.platform_uname]
system = "Linux"
node = "yuzj-pc"
release = "6.0.0-5-amd64"
version = "#1 SMP PREEMPT_DYNAMIC Debian 6.0.10-1 (2022-11-26)"
machine = "x86_64"
processor = ""
